---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(gtools)
library(tidyr)
library(Rcpp)
library(openxlsx)
```




```{r}
setwd("Downloads")
date1 = read.xlsx(xlsxFile="Assist Projections - All Games, modified inflow, with player tracking - Predicted Ramp.xlsx", sheet="Queue - HR ", startRow = 2, detectDates = TRUE, cols = c(1))
game1 = read.xlsx(xlsxFile="Assist Projections - All Games, modified inflow, with player tracking - Predicted Ramp.xlsx", sheet="Queue - HR ", startRow = 2, cols = c(3,seq(7,21)))
ArrivalTime = as.POSIXct(paste(date1$Date, "00:00:00 EST")) + 86400*(game1$Time)
game1[is.na.data.frame(game1)] = 0
game1$`PT.Danish.HRs-72`=game1$PT.Danish.HRs*(5/7)
game1$`PT.Danish.HRs-24`=game1$PT.Danish.HRs*(2/7)
game1$`PT.Champ.HRs-72`=game1$PT.Champ.HRs*(5/12)
game1$`PT.Champ.HRs-24`=game1$PT.Champ.HRs*(7/12)
df = data.frame(ArrivalTime, game1[c(2:14,17:20)])
df2 = df %>% gather(Type, TotalServerTime, -ArrivalTime) %>% filter(TotalServerTime!=0)
df2$ArrivalTime = as.POSIXct(df2$ArrivalTime , format = "%Y-%m-%d %h:%m:%s" , tz = "CDT") 
df2 = df2[ order(df2$ArrivalTime),]
cols = colnames(df)[2:18]
df2$TurnAround = ifelse(df2$Type %in% cols[c(1,4,7)],43200,ifelse(df2$Type %in% cols[c(2,5,8,10,11,12,13,15,17)],86400,ifelse(df2$Type %in% cols[c(3,6,9,14,16)],518400,0)))
df2$DueTime = df2$ArrivalTime + df2$TurnAround
df2$AveTime = ifelse(df2$Type %in% cols[c(1,2,3)],110/60,ifelse(df2$Type %in% cols[c(4,5,6)],10/60,ifelse(df2$Type %in% cols[c(7,8,9)],20/60,ifelse(df2$Type %in% cols[c(10,11,12,13)],130/60,ifelse(df2$Type %in% cols[c(14,15,16,17)],120/60,0)))))
df2$NumJobs = ceiling(df2$TotalServerTime/df2$AveTime)
df2$ServerTime = df2$TotalServerTime/df2$NumJobs
df2 = df2[rep(row.names(df2), df2$NumJobs),]
#df2$TotalTime = 3600*queue_step(arrivals = as.numeric(df2$ArrivalTime), service = df2$ServerTime, due = as.numeric(df2$DueTime), servers = 11)$departures_df$system_time
df2$TotalTime = 3600*finish_times(arrivals = as.numeric(df2$ArrivalTime), service = df2$ServerTime, due = as.numeric(df2$DueTime), servers = 11)$system_time
df2$ServerNum = queue_step(arrivals = as.numeric(df2$ArrivalTime), service = df2$ServerTime, due = as.numeric(df2$DueTime), servers = 11)$departures_df$server
df2$FinishTime = df2$ArrivalTime + df2$TotalTime
df2$StartTime = df2$FinishTime - 3600*df2$ServerTime
df2$OnTime = df2$DueTime > df2$FinishTime

mean(df2$OnTime[seq(1,500)])

as.numeric(dff$ArrivalTime)[1]-1501563500

dff = df2[1:60000,]

start=Sys.time()
algorithm2 = fin2(arrivals = as.numeric(dff$ArrivalTime)-1501563500, service = dff$ServerTime*3600, due = as.numeric(dff$DueTime)-1501563500, servers = 175)
Sys.time()-start
dff$TotalTime = algorithm3$system_time
dff$FinishTime = dff$ArrivalTime + dff$TotalTime
dff$StartTime = dff$FinishTime - 3600*dff$ServerTime
dff$OnTime = dff$DueTime > dff$FinishTime
dff$BeforeLastHour = dff$DueTime > dff$FinishTime + 3600
dff$BeforeLast4Hour = dff$DueTime > dff$FinishTime + 14400

mean(dff$OnTime[seq(1,150000)])
mean(dff$BeforeLastHour[seq(1,150000)])
mean(dff$BeforeLast4Hour[seq(1,150000)])

sum(dffd$StartTime<dffd$ArrivalTime)

dffd = df2

start=Sys.time()
algorithm4 = fin2(arrivals = as.numeric(dffd$ArrivalTime)-1501563500, service = dffd$ServerTime*3600, due = as.numeric(dffd$DueTime)-1501563500, servers = 180)
Sys.time()-start
dffd$TotalTime = algorithm4$system_time
dffd$FinishTime = dffd$ArrivalTime + dffd$TotalTime
dffd$StartTime = dffd$FinishTime - 3600*dffd$ServerTime
dffd$SevrerNum = algorithm4$server_num
dffd$OnTime = dffd$DueTime > dffd$FinishTime
dffd$BeforeLastHour = dffd$DueTime > dffd$FinishTime + 3600
dffd$BeforeLast4Hour = dffd$DueTime > dffd$FinishTime + 14400
dffd$Idle_Num = algorithm4$Idle_Num

mean(dffd$OnTime[seq(1,393789)])
mean(dffd$BeforeLastHour[seq(1,393789)])
mean(dffd$BeforeLast4Hour[seq(1,393789)])

11

arrivals = c(100,102,104,104,106,135,137,144,145,146,146)
service = c(7,3,4,7,10,4,6,4,4,4,4)
due = c(200,300,175,150,200,400,100,200,300,400,500)
servers = 2

arrivals = c(144,145,146,146,147)
service = c(4,4,4,4,4)
due = c(200,200,200,500,600)
servers = 2

arrivals = c(100,104,107,107)
service = c(6,.5,4,10)
due = c(200,150,100,55)
servers = 1

arrivals = c(100,100,110,115)
service = c(14,14,1,6)
due = c(1,1,1,1)
servers = 2

finish_times(arrivals, service, due, servers) == fin2(arrivals, service, due, servers)


fin2(arrivals, service, due, servers)










fin2 = function(arrivals, service, due, servers){
n = length(arrivals)
output = vector("numeric", (n+1) * 2 - 1)
queue_times = vector("numeric", servers)
due2 = due
arr = arrivals
ServerNum = c()
idle =c()
max_arr = 2*max(arrivals)
max_due = 2*max(due)
for (j in 1:n){
  if (j%%1000 == 0){
    print(j)
  }
    queue = which_minC(queue_times)
    min_arr = minC(arrivals)
    if (queue_times[queue] < min_arr){
      in_queue = which(arrivals==min_arr)
      i=in_queue[which_minC(due[in_queue])]
      idle[i] = sum(queue_times < arrivals[i])
      ServerNum[i] = queue
      queue_times[queue] = arrivals[i] + service[i]
      output[i] = queue_times[queue]
      output[i+n] = queue + 1
    } else{
        in_queue = which(arrivals<=queue_times[queue])
       i = in_queue[which_minC(due[in_queue])]
       idle[i] = sum(queue_times < arrivals[i])
        ServerNum[i] = queue
       queue_times[queue] = queue_times[queue] + service[i]
      output[i] = queue_times[queue]
      output[i+n] = queue + 1
    }
    arrivals[i]=max_arr
    due[i]=max_due
}
data = data.frame("arrivals"=arr,"service"=service,"departures"=output[1:length(arr)])
data$waiting = data$departures - data$service-data$arrivals
data$system_time = data$service + data$waiting
data$server_num = ServerNum
data$Idle_Num = idle
  return(data)
}





















finish_times = function(arrivals, service, due, servers){
  n = length(arrivals)
  output = vector("numeric", (n+1) * 2 - 1)
  queue_times = vector("numeric", servers)
  h=0
i=1
due2 = due
serv2 = service
arr = arrivals
arr2 = arrivals
ServerNum = c()
idle =c()
for (j in 1:length(arr2)){
  if (j%%1000 == 0){
    print(j)
  }
    idle[j] = sum(queue_times < arrivals[1])
    queue = which_minC(queue_times)
    ServerNum[j] = queue
    if (queue_times[queue] < arrivals[1]){
      i=which_minC(due[arrivals[1]>=arrivals])
      queue_times[queue] = maxC(c(arrivals[i], queue_times[queue])) + service[i]
      output[which(arr2==arrivals[i])[arr[which(arr2==arrivals[i])]==arrivals[i]][i]] = queue_times[queue]
      output[which(arr2==arrivals[i])[arr[which(arr2==arrivals[i])]==arrivals[i]][i]+n] = queue + 1
      arr2[which(arr2==arrivals[i])[arr[which(arr2==arrivals[i])]==arrivals[i]][i]]=queue_times[queue]
    } else{
       i = which_minC(due[arrivals<=queue_times[queue]])
       queue_times[queue] = queue_times[queue] + service[i]
       h = which(arrivals[i] == arr2)[which_minC(due2[which(arrivals[i] == arr2)])]
      arr2[h] = queue_times[queue]
      output[h] = queue_times[queue]
      output[h+n] = queue + 1
    }
    arrivals=arr[which(arr == arr2)]
    due=due2[which(arr == arr2)]
    service=serv2[which(arr == arr2)]
}
data = data.frame("arrivals"=arr,"service"=serv2,"departures"=output[1:length(arr)])
data$waiting = data$departures - data$service-data$arrivals
data$system_time = data$service + data$waiting
data$server_num = ServerNum
data$Idle_Num = idle
  return(data)
}





for(i in 1:n){
    queue = which.min(queue_times)
    queue_times[queue] = max(c(arrivals[i], queue_times[queue])) + service[i]
    
    if (queue_times[queue] < arrivals[i]){
      queue_times[queue] = max(c(arrivals[i], queue_times[queue])) + service[i]
    } else{
      arrivals[i:binsearch(function(y) arrivals[y]-queue_times[queue], range=c(1,           length(arrivals)))$where[1]][which.min(due[i:binsearch(function(y) arrivals[y]-queue_times[queue], range=c(1,length(arrivals)))$where[1]])]
      
      
    }
    
    output[i] = queue_times[queue]
    output[i + n] = queue + 1
  }






x <- c(4, 8, 15, 16, 23, 42)
binsearch(function(y) x[y]-24, range=c(1, length(x)))$where[1]

finish_times(arrivals, service, due, servers)


queue_step(arrivals = arrivals, service = service, due=due, servers = servers)

queue_pass(arrivals = arrivals, service = service, servers = servers)

queue(arrivals = arrivals, service = service, due=due, servers = servers)

df2[245:255,]

queue(arrivals = as.numeric(df2$ArrivalTime), service = df2$ServerTime, due = as.numeric(df2$DueTime), servers = 11)


ordstatement <- is.unsorted(arrivals)

  # Order arrivals and service according to time

  if(ordstatement){
    ord <- order(arrivals, method = "radix")
    due <- due[ord]
    arrivals <- arrivals[ord]
    service <- service[ord]
  }




qloop_numeric(arrivals, service, servers)


queue_lengths(due, 0, c(105,108,112,119,129))


arrivals <- cumsum(rexp(10))
service <- rexp(10)
queue_obj <- queue_step(arrivals, service, rev(arrivals))

depart(queue_obj)
queue_obj$departures_df$departures


queue_step(arrivals = as.numeric(df2$ArrivalTime), service = df2$ServerTime, due = as.numeric(df2$DueTime), servers = 100)$departures_df[572:582,]

queue_step(arrivals = as.numeric(df2$ArrivalTime[572:582]), service = df2$ServerTime[572:582], due = as.numeric(df2$DueTime[572:582]), servers = 1)$departures_df

toy = df2[,]

toy$AveTime = ifelse(df2$Type %in% cols[c(1,2,3)],110/60,ifelse(df2$Type %in% cols[c(4,5,6)],10/60,ifelse(df2$Type %in% cols[c(7,8,9)],20/60,ifelse(df2$Type %in% cols[c(10,11,12,13)],130/60,ifelse(df2$Type %in% cols[c(14,15,16,17)],120/60,0)))))

toy$NumJobs = ceiling(toy$TotalServerTime/toy$AveTime)
toy$ServerTime = toy$TotalServerTime/toy$NumJobs
toy = toy[rep(row.names(toy), toy$NumJobs),]

toy

```



```{r}
cppFunction('int which_minC(NumericVector x) {
  int n = x.size();
  double min = x[0];
  int ind = 1;
  for(int i = 1; i < n; ++i) {
    if ( x[i] < min) {
      min = x[i];
      ind = i+1;
    }
  }
  return ind;
}')

cppFunction('int which_maxC(NumericVector x) {
  int n = x.size();
  double max = x[0];
  int ind = 1;
  for(int i = 1; i < n; ++i) {
    if ( x[i] > max) {
      max = x[i];
      ind = i+1;
    }
  }
  return ind;
}')

which_minC(vector("numeric", 5))


cppFunction('double minC(NumericVector x) {
   int n = x.size();
   double min = x[0];
   for(int i = 1; i < n; ++i) {
     if ( x[i] < min)
       min = x[i];
   }
   return min;
}')

cppFunction('double maxC(NumericVector x) {
   int n = x.size();
   double max = x[0];
   for(int i = 1; i < n; ++i) {
     if ( x[i] > max)
       max = x[i];
   }
   return max;
}')

minC(c(1,2,5,-1,5,9,-9,5,-9,13))

cppFunction('NumericVector whichC(NumericVector x) {
   int n = x.size();
   NumericVector ind(n);
   for(int i = 0; i < n; ++i) {
     if (x[i])
       ind[i]=i+1;
   }
   return ind[ind!=0];
}')


xx= rep(0,100000)

start=Sys.time()
xxx=which(xx==xx)
Sys.time()-start






cppFunction('NumericVector Hudl(NumericVector x) {
   int n = x.size();
   NumericVector ind(n);
   for(int i = 0; i < n; ++i) {
     if (x[i])
       ind[i]=i+1;
   }
   return minC(x);
}')




n = length(arrivals)
output = vector("numeric", (n+1) * 2 - 1)
queue_times = vector("numeric", servers)
h=0
i=1
due2 = due
serv2 = service
arr = arrivals
arr2 = arrivals
for (j in 1:length(arr2)){
    queue = which_minC(queue_times)
    if (queue_times[queue] < arrivals[1]){
      i=which_minC(due[arrivals[1]>=arrivals])
      queue_times[queue] = maxC(c(arrivals[i], queue_times[queue])) + service[i]
      output[which(arr2==arrivals[i])[i]] = queue_times[queue]
      output[which(arr2==arrivals[i])[i]+n] = queue + 1
      arr2[which(arr2==arrivals[i])[i]]=queue_times[queue]
    } else{
       i = which_minC(due[arrivals<=queue_times[queue]])
       queue_times[queue] = queue_times[queue] + service[i]
       h = which(arrivals[i] == arr2)[which_minC(due2[which(arrivals[i] == arr2)])]
      arr2[h] = queue_times[queue]
      output[h] = queue_times[queue]
      output[h+n] = queue + 1
    }
    arrivals=arr[which(arr == arr2)]
    due=due2[which(arr == arr2)]
    service=serv2[which(arr == arr2)]
}
```








